import test from 'node:test';
import assert from 'node:assert/strict';
import { packSnapshot, validateData, publishSnapshot } from '../snapshot.mjs';
import { authorize } from '../server.mjs';
import { fixture } from '../../../apps/sohee/sales/tests/fixture.mjs';
const packed=()=>packSnapshot(fixture(),{capturedAt:'2026-04-16T12:00:00+09:00',sourceHashes:['a'.repeat(64)]});
function database(){const rows=new Map();return{rows,doc(path){return{path,get:async()=>({exists:rows.has(path),data:()=>rows.get(path)}),set:async value=>rows.set(path,value)};},async runTransaction(work){const pending=[];const value=await work({get:ref=>ref.get(),set:(ref,v)=>pending.push([ref.path,v])});for(const [k,v]of pending)rows.set(k,v);return value;}};}
test('reconciliation rejects invented totals, duplicate source dates and Payhere menu times',()=>{for(const kind of ['total','duplicate','payhere','partial']){const d=fixture();if(kind==='total')d.total++;if(kind==='duplicate')d.daily.push(d.daily[0]);if(kind==='payhere')d.menu_toss[0].date='2026-01-01';if(kind==='partial')d.menu_toss[0].date=d.partial_dates[0];assert.throws(()=>validateData(d));}});
test('published pointer is atomic, repeat import is idempotent, and conflicts preserve current',async()=>{const db=database(),p=packed();await publishSnapshot(db,p);const before=db.rows.get('sohee_sales/current');assert.equal((await publishSnapshot(db,p)).unchanged,true);assert.equal(before.revision,1);const changed=fixture();changed.generated_at='2026-04-17';const next=packSnapshot(changed,{capturedAt:'2026-04-17T12:00:00+09:00',sourceHashes:['b'.repeat(64)]});await assert.rejects(publishSnapshot(db,next,null),/REVISION_CONFLICT/);assert.deepEqual(db.rows.get('sohee_sales/current'),before);await publishSnapshot(db,next,p.version);assert.equal(db.rows.get('sohee_sales/current').revision,2);});
test('partial chunk failure and revoked authorization never move pointer',async()=>{const db=database(),p=packed();let calls=0;const normal=db.doc;db.doc=path=>{const ref=normal(path);if(path.includes('/chunks/'))ref.set=async()=>{throw new Error('offline');};return ref;};await assert.rejects(publishSnapshot(db,p));assert.equal(db.rows.has('sohee_sales/current'),false);db.doc=normal;await assert.rejects(publishSnapshot(db,p,null,async()=>{if(++calls>1)throw new Error('revoked');}));assert.equal(db.rows.has('sohee_sales/current'),false);});
test('server checks verified Google provider and fresh active membership',async()=>{const claims={uid:'synthetic-member',email_verified:true,firebase:{sign_in_provider:'google.com'}};const valid={token:'test-only',verifyToken:async()=>claims,readMember:async()=>({active:true,role:'sohee'})};assert.equal(await authorize(valid),'synthetic-member');for(const override of [{token:null},{verifyToken:async()=>({...claims,email_verified:false})},{verifyToken:async()=>({...claims,firebase:{sign_in_provider:'password'}})},{readMember:async()=>({active:false,role:'sohee'})},{readMember:async()=>({active:true,role:'other'})}])await assert.rejects(authorize({...valid,...override}));});
