// New editions use the same saved-selection contract as every existing design.
const palette = (id, name, paper, ink, accent, soft) => ({ id, name, paper, ink, accent, soft });
export const EDITIONS = [
  { id: 'magazine', name: '우리의 웨딩 매거진', english: 'The Sunday issue', number: '13', mood: '에디토리얼 · 대담한', description: '표지부터 인터뷰와 마지막 칼럼까지, 두 사람을 담은 한 권.', experienceHint: '인터뷰 기사 선택 · 지면을 따라 읽기', photoHint: '인물 화보와 일상 사진', galleryLayout: 'grid', tags: ['잡지', '인터뷰', '사진'], palettes: [palette('cherry', '체리', '#fffaf5', '#332b30', '#a22e48', '#f4e1e5'), palette('ink', '잉크', '#f9faff', '#27324b', '#3d5592', '#e5e9f4'), palette('leaf', '리프', '#f9fbf4', '#2d4334', '#476c49', '#e5eddc')] },
  { id: 'film', name: '천천히 현상되는 우리', english: 'In the light', number: '14', mood: '시네마틱 · 잔잔한', description: '암실에서 한 장씩 현상하는 사진과 이어지는 영화의 장면.', experienceHint: '사진 현상 · 콘택트 시트 장면 선택', photoHint: '빛과 여백이 있는 사진', galleryLayout: 'filmstrip', tags: ['필름', '영화', '사진'], palettes: [palette('silver', '실버', '#20242a', '#f5f2e9', '#cfb98a', '#343b43'), palette('plum', '플럼', '#30252f', '#fff4eb', '#dfb29b', '#483542'), palette('blue', '블루', '#182c3c', '#f2f5ed', '#a8c8d3', '#294352')] },
  { id: 'vinyl', name: '사랑의 B-side', english: 'Songs of our days', number: '15', mood: '음악 같은 · 아날로그', description: '레코드의 양면을 넘기며 듣는 대신 읽는 우리 이야기.', experienceHint: '레코드 돌리기 · A/B면과 트랙 선택', photoHint: '앨범 커버와 부클릿용 사진', galleryLayout: 'filmstrip', tags: ['음반', '음악', '레코드'], palettes: [palette('orange', '탠저린', '#fff5e5', '#363027', '#a04a27', '#f3ddbd'), palette('mint', '페일 민트', '#edf7f1', '#243d37', '#397862', '#d3e8de'), palette('rose', '더스티 로즈', '#fbefef', '#4b303d', '#945068', '#f0d9e0')] },
  { id: 'museum', name: '두 사람의 작은 전시', english: 'An exhibition of us', number: '16', mood: '갤러리 · 조용한', description: '작품을 감상하듯, 사진과 그 곁의 마음을 천천히 읽어요.', experienceHint: '전시실 이동 · 작품 해설 · 사진 확대', photoHint: '이야기가 담긴 사진 3장', galleryLayout: 'grid', tags: ['전시', '사진', '미니멀'], palettes: [palette('white', '갤러리 화이트', '#fffefa', '#34352f', '#66724d', '#edeee5'), palette('stone', '스톤', '#f4f3f0', '#353e43', '#617985', '#e3e8e9'), palette('peach', '피치', '#fff5ee', '#4e3830', '#966b51', '#f2e2d7')] },
  { id: 'greenhouse', name: '마음이 자라는 온실', english: 'A season together', number: '17', mood: '보태니컬 · 싱그러운', description: '계절을 바꾸고 꽃을 피우며 함께 가꾸는 하루를 만나요.', experienceHint: '계절 바꾸기 · 꽃 피우기', photoHint: '자연광과 정원의 사진', galleryLayout: 'grid', tags: ['정원', '꽃', '계절'], palettes: [palette('lime', '라임', '#f7fbe9', '#304930', '#527437', '#e2edc9'), palette('lilac', '라일락', '#f8f1fc', '#514363', '#8971a6', '#ebdff3'), palette('peach', '블룸', '#fff2e9', '#654535', '#a06b47', '#f1dfcd')] },
  { id: 'scrapbook', name: '우리의 수집 노트', english: 'Little things, kept', number: '18', mood: '콜라주 · 장난스러운', description: '사진과 작은 종이, 스티커로 모아둔 우리만의 추억장.', experienceHint: '추억 넘기기 · 스티커 붙이기', photoHint: '꾸밈없는 일상 스냅', galleryLayout: 'grid', tags: ['콜라주', '일기', '스티커'], palettes: [palette('pink', '버블 핑크', '#fff3f5', '#583e4d', '#a3496c', '#f6dfe8'), palette('sky', '스카이', '#f0f8fe', '#30465b', '#537fa2', '#dcecf7'), palette('lemon', '레몬', '#fffbe9', '#544d32', '#928043', '#f0e7c1')] },
  { id: 'festival', name: '오늘은 우리의 페스티벌', english: 'The love weekender', number: '19', mood: '축제 · 경쾌한', description: '라인업과 타임테이블, 기념 팔찌로 완성하는 축제의 초대.', experienceHint: '무대 일정 선택 · 기념 팔찌 꾸미기', photoHint: '웃음과 움직임이 있는 사진', galleryLayout: 'slide', tags: ['축제', '파티', '식순'], palettes: [palette('pop', '코랄 팝', '#fff4ec', '#4f3036', '#b7445d', '#f8ddc8'), palette('blue', '페스티벌 블루', '#f0f5ff', '#2e4270', '#476bbb', '#dae4ff'), palette('green', '잔디', '#f3fae9', '#344930', '#5b7a39', '#dceec5')] },
  { id: 'promenade', name: '너에게 가는 산책길', english: 'Meet me along the way', number: '20', mood: '지도 · 이야기', description: '처음 만난 길부터 함께할 내일까지, 멈춰 읽는 산책 지도.', experienceHint: '산책 지점 선택 · 길 따라 이야기 읽기', photoHint: '산책과 여행의 사진', galleryLayout: 'slide', tags: ['여행', '지도', '산책'], palettes: [palette('blue', '리버 블루', '#eff7fb', '#314c5b', '#4a7d96', '#dbeaf2'), palette('meadow', '메도', '#f5f8ec', '#455332', '#758549', '#e4ead1'), palette('sunset', '산책 노을', '#fff2eb', '#64493e', '#a47257', '#f2ded1')] },
].map(template => ({ ...template, collection: 'immersive', defaultSections: { story: true, rsvp: true, guestbook: true } }));
