const palette = (id, name, paper, ink, accent, soft) => ({ id, name, paper, ink, accent, soft });
export const REFERENCE_EDITIONS = [
  { id:'salon-lettering', number:'24', name:'살롱 · 사진 위에 쓴 초대', english:'Handwritten on our day', mood:'전면 사진 · 흰 레터링', description:'화면을 가득 채운 사진 위로 한 번 써지는 초대. 인물 소개와 인터뷰, 우리의 기록이 길게 이어져요.', experienceHint:'한 번 써지는 레터링 · 인물 소개 · 인터뷰', sourceBrand:'살롱드레터', sourceUrl:'https://salondeletter.com/w/iojsro5wcc', galleryLayout:'slide', palettes:[palette('original','화이트 레터링','#ffffff','#45413e','#c1a28f','#f7f3ef'),palette('rose','로즈 레터링','#fffafb','#4d4046','#af7f92','#f8ebf0'),palette('sage','세이지 레터링','#fbfdf9','#40483f','#839581','#edf2e9')] },
  { id:'salon-polaroid', number:'25', name:'살롱 · 하얀 사진 한 장', english:'A photo with a promise', mood:'폴라로이드 · 깨끗한', description:'얇은 그림자를 가진 하얀 사진 카드와 세로로 쓴 이름. 사진 사이의 넓은 여백을 따라 초대가 이어져요.', experienceHint:'폴라로이드 표지 · 사진 초대글 · 달력', sourceBrand:'살롱드레터', sourceUrl:'https://salondeletter.com/w/fpglo0twky', galleryLayout:'grid', palettes:[palette('original','페이퍼 화이트','#ffffff','#333333','#888888','#f5f5f5'),palette('blush','페이퍼 블러시','#fffafa','#4f4141','#aa7e84','#f7eeee'),palette('blue','페이퍼 블루','#fbfdff','#39474f','#7b939f','#edf3f7')] },
  { id:'salon-editorial', number:'26', name:'살롱 · 사진의 네 모서리', english:'The frame of our day', mood:'세로 타이포 · 모던한', description:'사진의 네 모서리에 두 사람의 이름과 날짜를 배치했어요. 짧은 오프닝을 지나 소개·기록·안내로 이어져요.', experienceHint:'한 번의 오프닝 · 모서리 타이포 · 사진 기록', sourceBrand:'살롱드레터', sourceUrl:'https://salondeletter.com/w/fb7i16olnt', galleryLayout:'slide', palettes:[palette('original','모던 화이트','#ffffff','#333333','#707070','#f3f3f3'),palette('cream','모던 크림','#fffdf7','#464239','#a38e62','#f5f0e5'),palette('mist','모던 미스트','#f8fcfc','#374a4b','#709596','#eaf2f1')] },
  { id:'guest-seoul', number:'27', name:'투아워게스트 · 서울', english:'Seoul · A film of us', mood:'흑백 필름 · 세로 사진', description:'흑백 사진 두 장과 세로로 놓인 작은 글씨. 큰 날짜와 인물 카드, 사진 기록을 차분하게 읽는 초대예요.', experienceHint:'두 장의 필름 표지 · 큰 날짜 · 사진 타임라인', sourceBrand:'투아워게스트', sourceUrl:'https://my.toourguest.com/preview/seoul', galleryLayout:'grid', palettes:[palette('original','서울 모노','#ffffff','#303030','#656565','#f1f1f1'),palette('cream','서울 크림','#fffdf9','#3e3934','#9b8b7d','#f3eee7'),palette('blue','서울 블루','#fafdff','#35464e','#78949f','#eaf1f4')] },
  { id:'guest-porto', number:'28', name:'투아워게스트 · 포르투', english:'Porto · A heart around us', mood:'손그림 하트 · 전면 사진', description:'사진을 크게 감싸는 흰 하트와 푸른빛 날짜 카드. 이어지는 이야기와 당일 안내를 넉넉한 여백에 담았어요.', experienceHint:'큰 손그림 하트 · 푸른 날짜 카드 · 인물 소개', sourceBrand:'투아워게스트', sourceUrl:'https://my.toourguest.com/preview/porto', galleryLayout:'slide', palettes:[palette('original','포르투 블루','#ffffff','#303638','#91a7b3','#e7eff2'),palette('rose','포르투 로즈','#fffafa','#514145','#b18d97','#f5e9ed'),palette('sage','포르투 세이지','#fcfdf9','#404b42','#8f9f87','#eef2e8')] },
  { id:'guest-jeju', number:'29', name:'투아워게스트 · 제주', english:'Jeju · Names in rose', mood:'장밋빛 · 이름과 여백', description:'장밋빛 화면에 두 사람의 이름만 크게 놓았어요. 흰 바탕의 긴 본문과 부드러운 사진 기록이 뒤를 이어요.', experienceHint:'장밋빛 타이포 표지 · 달력 · 사진 기록', sourceBrand:'투아워게스트', sourceUrl:'https://my.toourguest.com/preview/jeju', galleryLayout:'slide', palettes:[palette('original','제주 로즈','#ffffff','#373333','#b47b7b','#f7e7e7'),palette('blue','제주 블루','#fcfdff','#39434d','#8198b5','#e8eef6'),palette('green','제주 그린','#fcfdfb','#3e483e','#839b85','#eaf1e8')] },
].map(template=>({...template,collection:'reference',readingMode:'flow',tags:['원본','샘플',template.sourceBrand,'한번','긴본문'],photoHint:'예시 사진을 사용한 원본 구성 비교',defaultSections:{story:true,rsvp:true,guestbook:true}}));
export const isReferenceTemplate = id => REFERENCE_EDITIONS.some(template=>template.id===id);
