import React,{useState,useEffect,useContext,createContext} from 'react';
import {Button, Select, CheckField, QuantityField, BufferSlider, ExtraMenus} from './ui.jsx';
import {UpdatePanel} from './update-panel.jsx';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,Cell} from 'recharts';
import {Coffee,ArrowUpRight,Download,Check,CalendarDays,RotateCcw,Printer,Menu as MenuIcon} from 'lucide-react';
import {WEEKDAYS,WINDOWS,planRow,deadline} from './planning.mjs';

export const DataContext=createContext(null);
export const BASE='/sungso/sohee/sales/';
import {num,money,pct,colors,monthShort,sum,tipStyle,download,csv,Pill,Note,Section,Header,Stat,Table,numeric,textCol} from './report-ui.jsx';
import {Dashboard} from './overview.jsx';
import {SalesLedger} from './ledger.jsx';
import {DataStatus} from './data-status.jsx';
import {PeriodContext,DateFilter,usePeriod} from './date-filter.jsx';
import {initialSelection,selectedMenuData,groupMenus,selectionLabel} from './analysis.mjs';
import {internalSalesLink,salesRoute} from './navigation.mjs';
function Menus(){
  const D=useContext(DataContext),{selection}=usePeriod(), selectedData=selectedMenuData(D,selection);
  const [group,setGroup]=useState(true),[selected,setSelected]=useState(''),[metric,setMetric]=useState('amount');
  const key=group?'menu_group':'menu_original', grouped=groupMenus(selectedData.rows,key), menuAmount=sum(grouped,'amount');
  const rows=grouped.map(row=>({...row,share:menuAmount>0?row.amount/menuAmount*100:null})).sort((a,b)=>b[metric]-a[metric]);
  const names=rows.map(row=>row.menu);
  useEffect(()=>{if(!names.includes(selected))setSelected(names[0]||'')},[key,selection,D]);
  const monthly=[...new Set(D.monthly.map(row=>row.month))].map(month=>{const r=D.menu_monthly.filter(row=>row.month===month&&row[key]===selected);return {month,label:monthShort(month),amount:sum(r,'amount'),quantity:sum(r,'quantity')}});
  const detail=selectedData.detail.filter(row=>row[key]===selected);
  const hours=Array.from({length:24},(_,hour)=>({hour:hour+'시',quantity:sum(detail.filter(row=>row.hour===hour),'quantity')}));
  const dates=[...new Set(detail.map(row=>row.date))].sort().map(date=>({date,quantity:sum(detail.filter(row=>row.date===date),'quantity'),amount:sum(detail.filter(row=>row.date===date),'amount')}));
  return <><Header label="02 / MENU EXPLORER" title="메뉴 판매" description="무엇이 잘 팔리는지, 메뉴별 수량과 금액의 변화를 확인하세요."/><DateFilter data={D}/>
  <div className="toolbar"><Pill>{selectionLabel(selection)}</Pill><div className="segmented"><Button aria-pressed={metric==='amount'} className={metric==='amount'?'active':''} onClick={()=>setMetric('amount')}>매출순</Button><Button aria-pressed={metric==='quantity'} className={metric==='quantity'?'active':''} onClick={()=>setMetric('quantity')}>수량순</Button></div><CheckField label="아메리카노 명칭 통합" checked={group} onChange={event=>setGroup(event.target.checked)}/></div>
  <Note>{selectedData.dailyOnly?`일별 선택은 토스 완결일 메뉴 상세만 사용합니다. 페이히어 ${selectedData.omittedPayhereDays}일·부분일 ${selectedData.omittedPartialDays}일은 메뉴 집계에서 제외합니다.`:'월 단위 메뉴는 두 출처의 검증된 월별 집계를 사용합니다. 마지막 월은 부분일이 포함될 수 있습니다.'} ‘4구’ 수량은 팩 단위입니다.</Note>
  <div className="ledger-workbench menu-workbench"><Section title="메뉴별 판매 내역" desc="머리글로 정렬하거나 메뉴를 눌러 상세를 확인하세요."><Table data={rows} pageSize={7} columns={[{accessorKey:'menu',header:'메뉴',cell:item=><Button className="menu-link" aria-pressed={selected===item.getValue()} onClick={()=>setSelected(item.getValue())}>{item.getValue()}</Button>},numeric('quantity','판매 수량'),textCol('unit','단위'),numeric('amount','매출',money),numeric('share','메뉴 금액 비중',value=>value==null?'—':num(value,1)+'%'),numeric('average','수량당 매출',value=>value==null?'—':money(value))]} selectedRow={row=>row.menu===selected} filename="선택기간_메뉴.csv"/></Section>
  <Section title="메뉴 순위 10" desc="선택 기간 · 매출과 수량 순위를 전환할 수 있습니다."><div className="chart ranking"><ResponsiveContainer><BarChart data={rows.slice(0,10)} layout="vertical" margin={{left:0,right:24}} accessibilityLayer><CartesianGrid horizontal={false} stroke="var(--ss-border)" strokeDasharray="3 5"/><XAxis type="number" tickFormatter={value=>metric==='amount'?num(value/10000)+'만':num(value)} tickLine={false} axisLine={false}/><YAxis type="category" dataKey="menu" width={110} tickLine={false} axisLine={false} tick={{fontSize:11}}/><Tooltip contentStyle={tipStyle} formatter={(value,name,item)=>[metric==='amount'?money(value):num(value)+item.payload.unit,metric==='amount'?'매출':'수량']}/><Bar dataKey={metric} radius={[0,5,5,0]} isAnimationActive={false} onClick={row=>setSelected(row.menu)} cursor="pointer">{rows.slice(0,10).map((row,index)=><Cell key={row.menu} fill={index===0?colors[0]:colors[1]}/>)}</Bar></BarChart></ResponsiveContainer></div></Section></div>
  {selected&&<><Section title={selected+' · 월별 변화'} desc="전체 월별 이력입니다. 위 날짜 선택과 별도로 장기 흐름을 확인합니다." action={<Select label="메뉴 선택" value={selected} onChange={setSelected} options={names}/>}><div className="chart"><ResponsiveContainer><LineChart data={monthly} margin={{left:0,right:10,top:15}} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--ss-border)" strokeDasharray="3 5"/><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis yAxisId="left" tickFormatter={value=>num(value/10000)+'만'} tickLine={false} axisLine={false}/><YAxis yAxisId="right" orientation="right" tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={(value,name)=>[name==='매출'?money(value):num(value)+(selected.includes('4구')?'팩':'개'),name]}/><Legend/><Line yAxisId="left" name="매출" dataKey="amount" stroke={colors[0]} strokeWidth={2.5} dot={{r:3}} isAnimationActive={false}/><Line yAxisId="right" name="판매 수량" dataKey="quantity" stroke={colors[3]} strokeWidth={2} strokeDasharray="5 4" isAnimationActive={false}/></LineChart></ResponsiveContainer></div></Section>
  {!detail.length?<Note>선택한 날짜의 이 메뉴에는 토스 완결일 상세 기록이 없습니다. 페이히어의 메뉴 거래 시각은 추정하지 않습니다.</Note>:<div className="two-col"><Section title="선택일 메뉴 판매 시간" desc="토스 주문 시작 시각 · 대량 주문 포함 · 부분일 제외"><div className="chart"><ResponsiveContainer><BarChart data={hours} accessibilityLayer><CartesianGrid vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="hour" interval={3}/><YAxis/><Tooltip contentStyle={tipStyle} formatter={value=>[num(value)+(selected.includes('4구')?'팩':'개'),'판매 수량']}/><Bar dataKey="quantity" fill={colors[0]} radius={[4,4,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></Section><Section title="선택일 메뉴 판매 내역" desc="날짜별 정확한 수량과 금액"><Table data={dates} search={false} pageSize={7} columns={[textCol('date','날짜'),numeric('quantity','수량'),numeric('amount','매출',money)]}/></Section></div>}</>}
  </>;
}

function Prep(){
  const D=useContext(DataContext);
  const {selection}=usePeriod();const F=D.forecast;const actual=selectedMenuData(D,selection);const dessertNames=new Set(F.plans.map(row=>row.menu));const actualRows=groupMenus(actual.detail.filter(row=>dessertNames.has(row.menu_original)),'menu_original').sort((a,b)=>b.quantity-a.quantity);const [wd,setWd]=useState((new Date().getDay()+6)%7),[buffer,setBuffer]=useState(0),[lead,setLead]=useState(60),[view,setView]=useState('plan'),[manual,setManual]=useState({}),[extra,setExtra]=useState([]);
  const available=F.plans.filter(p=>p.weekday===wd).sort((a,b)=>b.expected-a.expected);
  const noSample=[...new Set(F.plans.map(p=>p.menu))].filter(m=>!available.some(p=>p.menu===m));
  const core=available.filter(p=>p.status==='준비 기준');const rare=available.filter(p=>p.status!=='준비 기준');
  const planned=[...core,...rare.filter(p=>extra.includes(p.menu))].map(p=>planRow(p,buffer,Object.hasOwn(manual,p.menu)?manual[p.menu]:null));
  const mainMetric=F.metrics.find(x=>x.menu==='전체')||{mae:null,baseline_mae:null,n:0,wape:null};
  const totals=WINDOWS.map((w,i)=>planned.reduce((s,r)=>s+r.windows[i]*(r.unit.includes('4개')?4:1),0));
  const prepExport=()=>download(`디저트_${WEEKDAYS[wd]}요일_당일준비.csv`,csv(planned.map(r=>({메뉴:r.menu,단위:r.unit,예상판매:r.expected,여유분퍼센트:buffer,당일준비:r.target,실물개수:r.physical,같은요일표본:r.same_weekday_days,...Object.fromEntries(WINDOWS.map((w,i)=>[w.label,r.windows[i]]))}))));
  const menus=[...new Set(F.plans.filter(p=>p.status==='준비 기준').map(p=>p.menu))];
  return <><Header label="03 / DESSERT PREPARATION" title="오늘 만들 디저트" description="당일 판매 원칙에 맞춘 요일별 준비 초안. 최근 토스 기록으로 계산합니다." action={<div className="head-actions"><Button className="outline" onClick={()=>window.print()}><Printer size={16}/> 인쇄</Button><Button className="primary" onClick={prepExport} disabled={!planned.length}><Download size={16}/> 준비표 저장</Button></div>}/>
  <div className="prep-summary"><div><Pill>당일 판매 · 이월 0</Pill><h2>조절 가능한 당일 준비 초안</h2><p>{F.cutoff}까지의 완결일 · 최근 {F.window_days}일 · 10만원 이상 주문 제외</p></div><div className="prep-total"><span>{WEEKDAYS[wd]}요일 당일 준비 초안</span><strong>{available.length?num(sum(planned,'physical')):'—'}<small>{available.length?'개':'표본 없음'}</small></strong><p>4구 상품은 4개로 환산 · 소량·신규 메뉴는 선택 추가</p></div></div>
  <div className="prep-controls"><div className="weekday-buttons" aria-label="준비 요일">{WEEKDAYS.map((w,i)=><Button key={w} className={i===wd?'active':''} onClick={()=>{setWd(i);setManual({})}} aria-pressed={wd===i}>{w}<small>요일</small></Button>)}</div><div className="adjust-controls"><div className="buffer-control"><div>여유분 <strong>{buffer}%</strong></div><BufferSlider value={buffer} onChange={setBuffer}/></div><div className="lead-control"><span>준비 소요 시간</span><QuantityField aria-label="준비 소요 시간 분" min={0} max={240} step={15} value={lead} onChange={v=>setLead(v)} suffix="분"/></div><Button className="text-button" onClick={()=>{setBuffer(0);setLead(60);setManual({});setExtra([])}}><RotateCcw size={15}/> 초기화</Button></div></div>
  <Note>과거 검증의 하루·메뉴 평균 오차는 {mainMetric.mae==null?"미검증":num(mainMetric.mae,2)}판매단위, 단순 최근 평균 오차는 {mainMetric.baseline_mae==null?"미검증":num(mainMetric.baseline_mae,2)}입니다. {mainMetric.mae==null?"검증할 표본이 부족합니다.":mainMetric.mae>=mainMetric.baseline_mae?"요일 모형이 단순 평균보다 정확하지 않습니다.":"검증 기간 밖의 정확도는 보장하지 않습니다."} 확정 생산량이 아닌 조절 가능한 초안입니다.</Note><div className="local-tabs"><Button aria-pressed={view==='plan'} className={view==='plan'?'active':''} onClick={()=>setView('plan')}>시간대별 준비표</Button><Button aria-pressed={view==='week'} className={view==='week'?'active':''} onClick={()=>setView('week')}>요일 비교</Button><Button aria-pressed={view==='accuracy'} className={view==='accuracy'?'active':''} onClick={()=>setView('accuracy')}>예측 검증</Button></div>
  {view==='plan'&&<>{!available.length?<Section title="이 요일은 계산할 기록이 부족합니다"><div className="empty"><CalendarDays size={32}/><p>최근 기간에 같은 요일의 매출 기록이 없습니다.<br/>예상 수량을 0으로 단정하지 않았습니다.</p></div></Section>:<>
  <Section title={`${WEEKDAYS[wd]}요일 준비표`} desc="각 시간대에 추가로 준비할 수량입니다. ‘당일 준비’를 직접 수정하면 시간대 수량도 함께 바뀝니다.">
  <p className="table-hint">좌우로 밀어 시간대별 수량을 확인하세요. 디저트 이름은 고정됩니다.</p><div className="table-scroll prep-table" tabIndex="0" role="region" aria-label="준비표 가로 스크롤"><table><thead><tr><th>디저트</th><th>예상 판매</th><th>당일 준비</th>{WINDOWS.map(w=><th key={w.label}>{w.label}<small>{w.start===0?"주문 별도 확인":deadline(w.start,lead)+" 준비 시작"}</small></th>)}<th>표본</th></tr></thead><tbody>{planned.map(r=><tr key={r.menu}><td><strong>{r.menu}</strong><small>{r.unit} {r.status==='참고용'?'· 표본 적음':''}</small></td><td>{num(r.expected,1)}</td><td><QuantityField min={0} max={999} aria-label={r.menu+' 당일 준비 수량'} value={r.target} onChange={v=>setManual({...manual,[r.menu]:v})}/></td>{r.windows.map((v,i)=><td key={i} className={v?'has-qty':''}>{v||'—'}</td>)}<td>{r.same_weekday_days}일<small>같은 요일</small></td></tr>)}</tbody><tfoot><tr><td colSpan="3">실물 개수 합계 <small>4구는 ×4</small></td>{totals.map((v,i)=><td key={i}>{v||'—'}</td>)}<td>{sum(planned,'physical')}개</td></tr></tfoot></table></div>
  {noSample.length>0&&<Note>이 요일 표본이 없어 수량을 제시하지 않은 메뉴: {noSample.join(', ')}. 최근에 등장한 메뉴는 며칠 더 기록이 쌓이면 계산할 수 있습니다.</Note>}<div className="prep-notes"><p><strong>수량 기준</strong> 평균 예상량을 반올림한 뒤 시간대 비중으로 배분했습니다. 각 시간대를 따로 올림해 당일 총량이 늘어나지 않게 했습니다.</p><p><strong>준비 시각</strong> 기본 60분은 가정입니다. 실제 제조 시간에 맞춰 조절하세요. 00–08시 칸은 밤·이른 아침 기록을 묶었으므로 주문 확인이 필요합니다.</p></div>
  {rare.length>0&&<ExtraMenus title={`신규·소량·최근 미판매 메뉴 ${rare.length}종`}><p>표본이 적거나 최근 14일간 판매가 없어 기본 준비표에서 제외했습니다. 선택하면 참고 수량을 더할 수 있습니다.</p><div className="rare-grid">{rare.map(r=><CheckField key={r.menu} checked={extra.includes(r.menu)} onChange={e=>setExtra(e.target.checked?[...extra,r.menu]:extra.filter(m=>m!==r.menu))} label={<span>{r.menu}<small>예상 {num(r.expected,1)}{r.unit} · 마지막 {r.last_observed.slice(5)}</small></span>}/>)}</div></ExtraMenus>}
  </Section><div className="two-col"><Section title="시간대별 준비 흐름" desc="4구를 낱개로 환산한 실물 기준"><div className="chart"><ResponsiveContainer><BarChart data={WINDOWS.map((w,i)=>({window:w.label,quantity:totals[i]}))}><CartesianGrid vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="window" tick={{fontSize:11}} interval={0} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={v=>[num(v)+'개','추가 준비']}/><Bar dataKey="quantity" fill={colors[0]} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Section><Section title="판매 편차도 함께 보기" desc="최근 같은 요일의 최저–최고 순수량. 예측 구간이나 품절 확률은 아닙니다."><div className="range-list">{core.map(r=><div key={r.menu}><span>{r.menu}</span><strong>{r.history_min}–{r.history_max}<small>{r.unit}</small></strong><span className="muted">예상 {num(r.expected,1)}</span></div>)}</div></Section></div></>}
  <Note>당일 판매량은 재고 소진으로 놓친 수요를 포함하지 못합니다. 예약·단체 주문은 이 초안에 별도로 더하세요. 보관 가능 시간과 제조 배치 제약이 없어 생산 최적화까지 계산한 값은 아닙니다.</Note></>}
  {view==='week'&&<Section title="같은 메뉴, 다른 요일" desc="여유분을 적용한 당일 총 준비 수량입니다. ‘—’는 해당 요일 표본 부족입니다."><p className="table-hint">표를 좌우로 밀어 모든 요일을 확인하세요.</p><div className="table-scroll" tabIndex="0" role="region" aria-label="요일별 표 가로 스크롤"><table className="week-heatmap"><thead><tr><th>메뉴</th>{WEEKDAYS.map(w=><th key={w}>{w}요일</th>)}</tr></thead><tbody>{menus.map(m=><tr key={m}><td>{m}<small>{F.plans.find(p=>p.menu===m).unit}</small></td>{WEEKDAYS.map((w,i)=>{const p=F.plans.find(p=>p.menu===m&&p.weekday===i);const n=p?planRow(p,buffer).target:null;return <td key={w} style={{background:n?`color-mix(in srgb, var(--ss-accent) ${Math.min(90,15+n*9)}%, var(--ss-surface))`:''}}>{n??'—'}</td>})}</tr>)}</tbody></table></div><Note>최근 같은 요일 평균과 전체 평균을 섞어, 몇 번의 판매가 요일 예측을 지나치게 바꾸지 않도록 했습니다. 품목별 첫 판매 이전 날짜는 0으로 넣지 않았습니다.</Note></Section>}
  {view==='accuracy'&&<><div className="stat-grid"><Stat label="하루·메뉴 평균 오차" value={mainMetric.mae==null?'—':num(mainMetric.mae,2)} unit="판매단위" detail={`${mainMetric.n}개 메뉴·날짜 조합에서 검증`}/><Stat label="단순 최근 평균 오차" value={mainMetric.baseline_mae==null?'—':num(mainMetric.baseline_mae,2)} unit="판매단위" detail="최근 28일 기록일 평균과 비교"/><Stat label="수량 기준 오차율" value={mainMetric.wape==null?'—':num(mainMetric.wape,1)} unit="%" detail="절대 오차 합계 ÷ 실제 판매 수량"/></div><Note><strong>현재 예측은 준비 초안으로 사용하세요.</strong> {mainMetric.mae==null?"검증할 표본이 부족합니다.":mainMetric.mae>=mainMetric.baseline_mae?"최근 검증에서 요일 모형이 단순 평균보다 정확하지 않았습니다.":"표시된 과거 검증의 정확도가 향후 판매를 보장하지 않습니다."} 예상 수량을 확정 생산량으로 해석하지 않습니다.</Note><Section title="과거 날짜를 하루씩 예측한 결과" desc={`${F.holdout_start}–${F.holdout_end} · 해당 날짜 이전 자료로만 계산 · 참고용 메뉴 제외`}><Table search={false} data={F.metrics.filter(x=>x.menu!=='전체')} columns={[textCol('menu','메뉴'),numeric('n','검증일'),numeric('mae','평균 오차',v=>num(v,2)),numeric('baseline_mae','단순 평균 오차',v=>num(v,2)),{accessorKey:'wape',header:'수량 오차율',cell:i=>i.getValue()==null?'분모 0':num(i.getValue(),1)+'%'}]}/><p className="footnote">오차 단위는 메뉴 판매단위입니다. 4구 상품 1단위의 오차는 낱개 4개의 차이를 뜻합니다. 특정 메뉴의 검증일이 적으면 비교도 불안정합니다.</p></Section><Section title="계산 기준"><ol className="method-list"><li><strong>최근 56일</strong><p>완결일만 사용하고 최근 기록에 더 큰 비중을 줍니다. 21일 전 기록의 비중은 최신 기록의 절반입니다.</p></li><li><strong>비슷한 요일 + 최근 전체</strong><p>같은 요일 표본 n일의 가중치는 n / (n + 4). 나머지는 전체 요일 평균으로 보완합니다.</p></li><li><strong>일반 판매 흐름</strong><p>총액 10만원 이상 주문은 제외합니다. 해당 메뉴 판매가 없는 매출 기록일은 0으로 포함하고, 첫 판매 이전은 제외합니다.</p></li><li><strong>시간 배분</strong><p>같은 방식의 시간별 판매 비중으로 하루 수량을 나눕니다. 전체 수량은 반올림하고 잔여 수량을 소수 부분이 큰 시간대에 배분합니다.</p></li></ol><a className="source-link" href="https://otexts.com/fpp3/tscv.html" target="_blank" rel="noreferrer">검증 방법 참고: Forecasting — Time series cross-validation <ArrowUpRight size={14}/></a></Section></>}
  <ExtraMenus title="과거 판매와 비교하기"><DateFilter data={D}/><Note>날짜 선택은 실제 판매에 적용됩니다. 준비 초안은 {F.cutoff}까지 최근 {F.window_days}일 기준이며 선택 기간으로 다시 학습하지 않습니다.</Note><Section title="준비 메뉴의 선택일 실제 판매" desc="토스 완결일 상세만 집계 · 부분일과 페이히어 제외 · 생산량이나 폐기량이 아닙니다."><Table search={false} pageSize={5} data={actualRows} columns={[textCol('menu','메뉴'),numeric('quantity','판매 수량'),textCol('unit','단위'),numeric('amount','매출',money)]}/></Section></ExtraMenus>
  <div className="footnote">수정한 수량은 이 화면에서만 유지됩니다. 준비표 저장으로 현재 선택값을 보관할 수 있습니다. 전날 재고는 모든 계산에서 0입니다.</div>
  </>
}

function Changes(){
 const D=useContext(DataContext);
 const bulk=D.existing.monthly_large_order_sensitivity||[], am=D.existing.americano_before_after_28d||[];
 const change=(after,before)=>before?(after/before-1)*100:null;
 const amChange=key=>am.length===2?change(am[1][key],am[0][key]):null;
 return <Dashboard data={D}><ExtraMenus title="과거 변화와 비교 근거">
 <Section title="월별 대량 주문 이력" desc="전체 월별 이력 · 위 날짜 선택과 별도 · 토스 10만원 이상 주문"><div className="chart"><ResponsiveContainer><BarChart data={bulk}><CartesianGrid vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>num(v/10000)+'만'}/><Tooltip contentStyle={tipStyle} formatter={(v,n)=>[money(v),n]}/><Legend/><Bar stackId="a" name="일반 주문" dataKey="sales_without_100k_orders" fill={colors[0]}/><Bar stackId="a" name="10만원 이상 주문" dataKey="large_order_sales" fill={colors[3]}/></BarChart></ResponsiveContainer></div><Table search={false} data={bulk} columns={[textCol('month','월'),numeric('all_sales','전체',money),numeric('sales_without_100k_orders','대량 주문 제외',money),numeric('large_order_count','큰 주문 건수')]}/></Section>
 <Section title="아메리카노 포장할인 변화" desc="과거 비교 자료 · 관찰된 판매 명칭의 전환이며 실제 정책 변경일이 아닙니다.">{am.length?<><Table search={false} data={am} columns={[textCol('start','시작'),textCol('end','종료'),numeric('store_payment_days','기록일'),numeric('net_per_unit','수량당 매출',money),numeric('quantity_per_store_day','기록일당 수량',v=>num(v,1))]}/><div className="mini-metrics">{[['수량당 매출','net_per_unit'],['기록일당 수량','quantity_per_store_day'],['기록일당 매출','sales_per_store_day']].map(([label,key])=><div key={key}><span>{label}</span><strong>{amChange(key)==null?'—':pct(amChange(key))}</strong></div>)}</div></>:<Note>비교 원본이 없어 변화율을 계산하지 않았습니다.</Note>}<Note>원래 메뉴명·단가를 보존합니다. 가격 변화만으로 매출 증가나 개인의 성과를 단정하지 않습니다.</Note></Section>
 <Section title="포트폴리오 근거 체크" desc="매출 자료는 공개 포트폴리오에 자동 전달되지 않습니다."><ol className="method-list"><li><strong>활동 날짜 확인</strong><p>신메뉴·진열·홍보·단체 주문 제안의 실제 실행 날짜와 본인의 역할을 확인합니다.</p></li><li><strong>같은 조건으로 비교</strong><p>기록일 수·메뉴 구성·대량 주문·POS 전환을 함께 확인합니다.</p></li><li><strong>근거를 대조</strong><p>사진·게시물·운영 일지와 매출 변화 시점을 대조합니다.</p></li><li><strong>공개할 문장 별도 검토</strong><p>검증된 사실만 골라 외부 공개 여부를 결정합니다.</p></li></ol><a className="outline" href="/sungso/sohee/portfolio/">포트폴리오 구성 예시 보기 <ArrowUpRight size={16}/></a></Section>
 </ExtraMenus></Dashboard>
}
function DataPage(){
 const D=useContext(DataContext);
 return <><Header label="05 / DATA LIBRARY" title="수집 범위와 데이터 관리" description="앞으로는 토스 원본만 갱신합니다. 과거 페이히어 자료는 보존합니다."/>
 <p className="footnote">이 화면의 출처·수집 범위는 전체 저장 자료 기준입니다. 새 자료 수집은 요청할 때 로컬 PC에서 진행합니다.</p><UpdatePanel/>
 <div className="source-cards"><Section title="토스 · 앞으로의 기록" desc={`상세 원본 마지막 날짜 ${D.end}`}><Pill>완결일 {D.complete_through}까지</Pill><ul className="plain-list"><li>메뉴별 날짜·주문 시간·수량·금액</li><li>중복되는 날짜 범위만 교체·누적</li><li>부분일: {D.partial_dates.join(', ')||'없음'}</li></ul><Note>앱 화면에서 확인한 합계는 상세 거래를 대체하지 않습니다. 새 토스 원본을 받아 검증하기 전에는 매출을 보충하지 않습니다.</Note></Section><Section title="페이히어 · 과거 기록" desc="보관된 원본과 월별 화면을 대조한 자료"><ul className="plain-list"><li>과거 일별·월별 매출과 월별 메뉴 수량</li><li>메뉴별 거래 시각은 제공되지 않음</li><li>메뉴 시간대·준비 예측은 토스만 사용</li></ul><Note>4구 상품은 1팩이 1판매단위입니다. 준비표에서만 실물 4개로 구분합니다.</Note></Section></div>
 <Section title="갱신·수집 범위"><Table search={false} data={D.monthly} columns={[textCol('month','기간'),textCol('source','출처'),numeric('record_days','기록일'),{accessorKey:'partial',header:'수집 상태',cell:i=>i.getValue()?'부분월':'수집 완료'}]}/><p className="footnote">분석 생성일 {D.generated_at} · 분석 생성일과 원본 수집일은 다를 수 있습니다.</p></Section>
 <Section title="원본 대조 기록"><div className="validation-grid">{D.files.map(f=><div key={f.file}><Check size={20}/><div><strong>{f.file}</strong><p>{f.start}–{f.end}</p><small>SHA-256 {f.sha256.slice(0,16)}…</small></div></div>)}</div><div className="download-row"><Button className="outline" onClick={()=>download('통합_일별매출.csv',csv(D.daily))}><Download size={16}/> 일별 매출 CSV</Button><Button className="outline" onClick={()=>download('통합_메뉴월별.csv',csv(D.menu_monthly))}>메뉴 월별 CSV</Button><Button className="outline" onClick={()=>download('예측검증.csv',csv(D.forecast.metrics))}>예측 검증 CSV</Button></div><Note>다운로드 파일에는 비공개 매출이 포함됩니다. 파일의 공유 범위를 직접 확인하세요.</Note></Section>
 <Section title="해석의 한계"><ul className="plain-list"><li>기록 없는 날은 휴무로 단정하지 않습니다.</li><li>원가·폐기·품절 기록이 없어 이익이나 놓친 수요를 계산하지 않습니다.</li><li>기여 시점·운영 변경일은 미확인입니다.</li><li>예측 오차와 표본 부족을 준비 화면에서 함께 표시합니다.</li></ul></Section></>
}
const pages=[{id:'changes',label:'대시보드',component:Changes},{id:'overview',label:'매출 내역',component:SalesLedger},{id:'menus',label:'메뉴 판매',component:Menus},{id:'prep',label:'디저트 준비',component:Prep},{id:'data',label:'자료 기준',component:DataPage,hidden:true}];
export function SalesApp({data,route:initialRoute='changes',status='Firebase 회원 전용'}){
 const [navOpen,setNavOpen]=useState(false),[route,setRoute]=useState(initialRoute);
 const [selection,setSelection]=useState(()=>data?initialSelection(data):null);
 useEffect(()=>setRoute(initialRoute),[initialRoute]);
 useEffect(()=>{const back=()=>setRoute(salesRoute(window.location.pathname)||'changes');window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back)},[]);
 function navigate(event){const url=internalSalesLink(event,window.location.origin);if(!url)return;event.preventDefault();window.history.pushState(null,'',url.pathname+url.search);setRoute(salesRoute(url.pathname));setNavOpen(false);window.scrollTo(0,0);document.getElementById('main')?.focus({preventScroll:true})}
 const selected=pages.find(p=>p.id===route); const Page=selected?.component;
 useEffect(()=>{document.title=`${selected?.label||'페이지 없음'} · 양정커피`;},[route]);
 return <DataContext.Provider value={data}><PeriodContext.Provider value={{selection:selection||(data?initialSelection(data):null),setSelection}}><div className={'app page-'+route} onClick={navigate}>
  <a href="#main" className="skip-link">본문으로 이동</a>
  <header className="app-header"><div className="app-identity"><a href={BASE} className="brand"><span className="brand-mark"><Coffee size={24}/></span><strong>양정커피</strong></a><a className="workspace-link" href="/sungso/sohee/workspace/">소희 작업실</a></div><span className="connection-status">{status}</span></header>
  <div className="navigation-shell"><Button className="mobile-menu" aria-label="페이지 메뉴" aria-expanded={navOpen} aria-controls="sales-navigation" onClick={()=>setNavOpen(!navOpen)}><span>{selected?.label||'매출 분석'}</span><MenuIcon size={20}/></Button><nav id="sales-navigation" aria-label="매출 분석" className={'primary-nav '+(navOpen?'open':'')}>{pages.filter(p=>!p.hidden).map(p=><a href={BASE+p.id+'/'} key={p.id} className={route===p.id?'active':''} aria-current={route===p.id?'page':undefined} onClick={()=>setNavOpen(false)}>{p.label}</a>)}</nav></div>
  <main id="main" tabIndex="-1"><div className="page-content">{!Page?<Section title="페이지를 찾을 수 없어요"><a href={BASE}>대시보드로</a></Section>:!data?<><Header title="아직 저장된 매출이 없습니다" description="회원 전용 Firebase 저장소를 확인했습니다. 검증된 분석본을 이전하거나 새 원본을 가져오면 표시됩니다."/><UpdatePanel/></>:<Page data={data}/>}</div><footer>양정커피 <span>매출을 읽고, 오늘의 준비를 결정합니다.</span><DataStatus data={data}/></footer></main>
 </div></PeriodContext.Provider></DataContext.Provider>
}
export class ErrorBoundary extends React.Component{constructor(p){super(p);this.state={error:false}}static getDerivedStateFromError(){return {error:true}}render(){return this.state.error?<div className="empty"><h1>화면을 불러오지 못했습니다.</h1><p>저장된 자료의 형식을 확인해주세요.</p><Button onClick={()=>location.reload()}>새로고침</Button></div>:this.props.children}}
