import React,{useState,useMemo,useEffect,useContext,createContext} from 'react';
import {Button, Select, SearchField, CheckField, QuantityField, BufferSlider, ExtraMenus, SalesCalendar} from './ui.jsx';
import {UpdatePanel} from './update-panel.jsx';
import {ResponsiveContainer,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,Cell,ReferenceLine} from 'recharts';
import {useReactTable,getCoreRowModel,getSortedRowModel,getFilteredRowModel,getPaginationRowModel,flexRender} from '@tanstack/react-table';
import {Coffee,LayoutDashboard,ChartNoAxesCombined,Croissant,Database,ArrowUpRight,ChevronLeft,ChevronRight,Download,Search,Info,Check,CalendarDays,RotateCcw,Printer,Menu as MenuIcon} from 'lucide-react';
import {WEEKDAYS,WINDOWS,planRow,deadline} from './planning.mjs';

const DataContext=createContext(null);
export const BASE='/sungso/sohee/sales/';
const num=(v,d=0)=>Number(v||0).toLocaleString('ko-KR',{maximumFractionDigits:d,minimumFractionDigits:d});
const money=v=>num(v)+'원';
const pct=v=>(v>0?'+':'')+num(v,1)+'%';
const sourceName=s=>s==='toss'?'Toss POS':'Payhere';
const colors=['var(--ss-link)','var(--ss-accent)','var(--ss-muted)','var(--ss-text)','var(--ss-border-strong)'];
const monthShort=m=>m.slice(2,4)+'.'+m.slice(5);
const sum=(a,k)=>a.reduce((s,r)=>s+Number(r[k]||0),0);
const tipStyle={border:'1px solid var(--ss-border)',borderRadius:6,fontSize:13,boxShadow:'0 8px 24px var(--ss-shadow)'};


function download(filename,content,type='text/csv;charset=utf-8'){
  const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);
}
function csv(rows){if(!rows.length)return '';const keys=Object.keys(rows[0]);const quote=v=>{let s=String(v??'');if(typeof v==='string'&&/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};return '\ufeff'+[keys,...rows.map(r=>keys.map(k=>r[k]))].map(row=>row.map(quote).join(',')).join('\r\n')}
function Pill({children,kind=''}){return <span className={'pill '+kind}>{children}</span>}
function Note({children}){return <div className="note"><Info size={16}/><div>{children}</div></div>}
function Section({eyebrow,title,desc,action,children,className=''}){return <section className={'panel '+className}><div className="section-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2>{desc&&<p>{desc}</p>}</div>{action}</div>{children}</section>}
function Header({label,title,description,action}){return <header className="page-head"><div><div className="eyebrow page-label">{label}</div><h1>{title}</h1><p>{description}</p></div>{action}</header>}
function Stat({label,value,unit,detail,icon:Icon=ChartNoAxesCombined,accent=false}){return <div className={'stat '+(accent?'accent':'')}><div className="stat-label">{label}<Icon size={18}/></div><div className="stat-value">{value}<span>{unit}</span></div><p>{detail}</p></div>}

function Table({data,columns,search=true,filename='분석.csv',pageSize=10,initialSort=[],searchPlaceholder='메뉴·날짜 검색',selectedRow}){
  const [sorting,setSorting]=useState(initialSort),[filter,setFilter]=useState('');
  const table=useReactTable({data,columns,state:{sorting,globalFilter:filter},onSortingChange:setSorting,onGlobalFilterChange:setFilter,getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),initialState:{pagination:{pageSize}}});
  return <div className="data-table">{search&&<div className="table-tools"><SearchField placeholder={searchPlaceholder} value={filter} onChange={e=>setFilter(e.target.value)}/><Button className="text-button" onClick={()=>download(filename,csv(table.getFilteredRowModel().rows.map(x=>x.original)))}><Download size={16}/> CSV</Button></div>}<p className="table-hint">표가 잘리면 좌우로 밀어 나머지 열을 확인하세요.</p><div className="table-scroll" tabIndex="0" role="region" aria-label="표 가로 스크롤"><table><thead>{table.getHeaderGroups().map(h=><tr key={h.id}>{h.headers.map(c=><th key={c.id} className={c.column.columnDef.meta?.numeric?'numeric-cell':undefined} aria-sort={c.column.getIsSorted()==='desc'?'descending':c.column.getIsSorted()==='asc'?'ascending':'none'}><Button onClick={c.column.getToggleSortingHandler()}>{flexRender(c.column.columnDef.header,c.getContext())}<span className="sortmark">{c.column.getIsSorted()==='desc'?' ↓':c.column.getIsSorted()==='asc'?' ↑':' ↕'}</span></Button></th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(r=><tr key={r.id} className={selectedRow?.(r.original)?'selected-row':undefined}>{r.getVisibleCells().map(c=><td key={c.id} className={c.column.columnDef.meta?.numeric?'numeric-cell':undefined}>{flexRender(c.column.columnDef.cell,c.getContext())}</td>)}</tr>)}</tbody></table>{!table.getRowModel().rows.length&&<div className="empty">해당 조건에 맞는 기록이 없습니다.</div>}</div><div className="pagination"><span>{num(table.getFilteredRowModel().rows.length)}개 기록</span><div><Button aria-label="이전 표 페이지" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}><ChevronLeft size={17}/></Button><span>{table.getState().pagination.pageIndex+1} / {Math.max(1,table.getPageCount())}</span><Button aria-label="다음 표 페이지" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}><ChevronRight size={17}/></Button></div></div></div>
}
const numeric=(id,title,format=num)=>({accessorKey:id,header:title,meta:{numeric:true},cell:i=><span className="number">{format(i.getValue())}</span>});
const textCol=(id,title)=>({accessorKey:id,header:title});

function Overview(){
  const D=useContext(DataContext); const monthOptions=D.monthly.map(x=>x.month);
  const [month,setMonth]=useState(D.monthly.at(-1).month),[basis,setBasis]=useState('total');
  const selected=D.monthly.find(x=>x.month===month),daily=D.daily.filter(x=>x.month===month);
  const comparison=D.comparison,delta=comparison.change_pct;
  const chart=D.monthly.map(x=>({...x,label:monthShort(x.month),value:basis==='total'?x.amount:x.per_record_day}));
  const hourly=Array.from({length:24},(_,hour)=>({hour:hour+'시',amount:sum(D.receipt_hour.filter(x=>x.month===month&&x.hour===hour),'amount')})).filter((x,h)=>h>=6&&h<=22);
  return <><Header label="01 / SALES OVERVIEW" title="매출 원장과 추이" description="월별 원장을 중심으로, 매출과 기록일당 흐름을 함께 확인하세요." action={<Pill><CalendarDays size={16}/>원본 {D.end} · 완결일 {D.complete_through}</Pill>}/>
  <section className="comparison-strip" aria-label="최근 완결일 비교">
    <div className="comparison-period"><span>최근 완결일 비교</span><strong>{comparison.current_start.slice(5)}–{comparison.current_end.slice(5)}</strong><small>이전 {comparison.previous_start.slice(5)}–{comparison.previous_end.slice(5)}</small></div>
    <div><span>매출</span><strong>{num(comparison.current_amount)}<em>원</em></strong><small>이전 {money(comparison.previous_amount)}</small></div>
    <div><span>이전 동기간 대비</span><strong className="comparison-change">{delta==null?'—':pct(delta)}</strong><a href={BASE+'changes/'}>변화의 배경 <ArrowUpRight size={14}/></a></div>
    <div><span>기록일당 매출</span><strong>{comparison.current_days?num(comparison.current_amount/comparison.current_days):'—'}<em>원</em></strong><small>이전 {comparison.previous_days?money(comparison.previous_amount/comparison.previous_days):'—'} · {comparison.per_day_change_pct==null?'비교 불가':pct(comparison.per_day_change_pct)}</small></div>
    <div className="comparison-days"><span>매출 기록일 기준</span><strong>{comparison.current_days}일 / {comparison.previous_days}일</strong><small>부분일 제외 · 영업일 확정값 아님</small></div>
  </section>
  <div className="ledger-workbench">
    <Section title="월별 원장" desc="월을 선택해 매출·기록일·상세 추이를 확인하세요." className="ledger-table"><Table data={D.monthly} columns={[
      {accessorKey:'month',header:'기간',cell:i=><Button className="menu-link" aria-pressed={month===i.getValue()} onClick={()=>setMonth(i.getValue())}>{i.getValue()}</Button>},
      {accessorKey:'source',header:'출처',cell:i=>sourceName(i.getValue())},numeric('amount','매출',money),numeric('record_days','기록일'),numeric('per_record_day','기록일당 매출',money),
      {accessorKey:'partial',header:'범위',cell:i=>i.getValue()?<Pill kind="warn">부분월</Pill>:'수집 완료'}
    ]} filename="월별_매출.csv" searchPlaceholder="월 검색 (예: 2026-09)" selectedRow={r=>r.month===month} initialSort={[{id:'month',desc:true}]}/><p className="footnote">수집 범위 {D.start}–{D.end} · 출처별 실매출 표시 기준을 유지합니다.</p></Section>
    <Section title="선택 월 살펴보기" className="month-detail" action={<Select label="월" value={month} onChange={setMonth} options={monthOptions}/>}>
      <div className="selected-month-summary"><strong>{selected.partial?'부분월 포함':'수집 완료'} · 총 {money(selected.amount)}</strong><span>{selected.record_days}개 기록일 · {sourceName(selected.source)}</span></div>
      <div className="detail-chart"><div className="chart-heading"><h3>일별 매출 추이</h3><span>{month} · 단위 만원</span></div><div className="chart compact"><ResponsiveContainer><LineChart data={daily} margin={{left:-18,right:12,top:15,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="var(--ss-border)"/><XAxis dataKey="date" tickFormatter={v=>v.slice(8)} tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>num(v/10000)} tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={(v,n,p)=>[money(v),p.payload.partial_day?'부분일 매출':'매출']}/><Line dataKey="amount" stroke={colors[0]} strokeWidth={2} dot={({cx,cy,payload})=><circle key={payload.date} cx={cx} cy={cy} r={payload.partial_day?5:2.5} fill={payload.partial_day?'var(--ss-surface)':colors[0]} stroke={colors[0]} strokeWidth={1.5}/>}/></LineChart></ResponsiveContainer></div><p className="chart-caption">{daily.some(d=>d.partial_day)?'빈 원은 부분일입니다. 당일 전체 매출과 직접 비교하지 마세요.':'기록 없는 날을 휴무로 단정하지 않습니다.'}</p></div>
      <div className="detail-chart"><div className="chart-heading"><h3>결제 시간대별 매출</h3><span>완결일만 집계</span></div><div className="chart compact"><ResponsiveContainer><BarChart data={hourly} margin={{left:-18,right:12,top:15,bottom:0}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="var(--ss-border)"/><XAxis dataKey="hour" interval={2} tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>num(v/10000)+'만'} tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={v=>[money(v),'결제 매출']}/><Bar dataKey="amount" fill={colors[1]} radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div><p className="chart-caption">결제 시각 기준 · 메뉴 준비 분석은 토스 주문 시작 시각을 사용합니다.</p></div>
    </Section>
  </div>
  <Note>수집 기준 · Payhere 환불은 실매출에서 다시 빼지 않습니다. 토스는 결제·환불한 날에 부호를 반영합니다. 원가 자료가 없어 순이익은 계산하지 않습니다.</Note>
  <div className="two-col overview-secondary">  <Section title="월별 매출" desc={basis==='total'?'옅은 막대는 부분월입니다. 월 합계를 비교할 때 수집 범위를 확인하세요.':'월별 매출을 매출 기록이 있는 날로 나눈 값입니다. 영업일 확정 값과는 다를 수 있습니다.'} action={<div className="segmented"><Button aria-pressed={basis==='total'} className={basis==='total'?'active':''} onClick={()=>setBasis('total')}>월 합계</Button><Button aria-pressed={basis==='daily'} className={basis==='daily'?'active':''} onClick={()=>setBasis('daily')}>기록일당</Button></div>}>
  <div className="chart tall"><ResponsiveContainer><BarChart data={chart} margin={{top:12,right:20,left:0,bottom:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickFormatter={v=>num(v/10000)+'만'} tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={v=>[money(v),basis==='total'?'매출':'기록일당 매출']}/><ReferenceLine x={monthShort(D.monthly.find(x=>x.source==='toss')?.month||D.end.slice(0,7))} stroke="var(--ss-border-strong)" strokeDasharray="4 4" label={{value:'Toss 시작',position:'insideTopRight',fontSize:12,fill:'var(--ss-muted)'}}/><Bar dataKey="value" radius={[5,5,0,0]} maxBarSize={44}>{chart.map(x=><Cell key={x.month} fill={x.source==='toss'?colors[0]:colors[1]} fillOpacity={x.partial?.55:1}/>)}</Bar></BarChart></ResponsiveContainer></div><div className="legend"><span><i style={{background:colors[1]}}/>Payhere</span><span><i style={{background:colors[0]}}/>Toss POS</span><span className="muted">{D.partial_dates.length?monthShort(D.partial_dates.at(-1).slice(0,7))+' 부분월':'완결일 집계'}</span></div>
  </Section>
<Section title="매출 달력" desc="배경이 진할수록 매출이 높은 날입니다." action={<Pill>{month}</Pill>}> <SalesCalendar months={monthOptions} month={month} onMonthChange={setMonth} daily={daily} start={D.start} end={D.end}/><p className="footnote">기록이 없는 날은 휴무로 단정하지 않습니다. 마지막 수집일 이후는 계산하지 않습니다.</p></Section></div>
  </>
}

function Menus(){
  const D=useContext(DataContext); const monthOptions=D.monthly.map(x=>x.month);
  const [period,setPeriod]=useState('all'),[group,setGroup]=useState(true),[selected,setSelected]=useState(D.menu_monthly[0]?.menu_group||''),[metric,setMetric]=useState('amount'),[trendMonth,setTrendMonth]=useState('all');
  const key=group?'menu_group':'menu_original';
  const rows=useMemo(()=>{const map=new Map();D.menu_monthly.filter(x=>period==='all'||x.month===period).forEach(x=>{const n=x[key],old=map.get(n)||{menu:n,amount:0,quantity:0,categories:new Set()};old.amount+=x.amount;old.quantity+=x.quantity;old.categories.add(x.category);map.set(n,old)});return [...map.values()].map(x=>({...x,category:[...x.categories].join(' · '),unit:x.menu.includes('4구')?'팩 (4개)':'개',average:x.quantity>0?x.amount/x.quantity:0})).sort((a,b)=>b[metric]-a[metric])},[period,key,metric]);
  const menuNames=useMemo(()=>[...new Set(D.menu_monthly.map(x=>x[key]))].sort((a,b)=>a.localeCompare(b,'ko')),[key]);
  useEffect(()=>{if(!menuNames.includes(selected))setSelected(menuNames.includes('아메리카노 통합')?'아메리카노 통합':menuNames[0])},[group]);
  const monthly=monthOptions.map(m=>{const r=D.menu_monthly.filter(x=>x.month===m&&x[key]===selected);return {month:m,label:monthShort(m),amount:sum(r,'amount'),quantity:sum(r,'quantity')}});
  // For ungrouped names, the detail is rebuilt by filtering grouped aggregation only if exact group exists.
  const detail=D.menu_toss.filter(x=>x[key]===selected&&(trendMonth==='all'||x.date.startsWith(trendMonth)));
  const hours=Array.from({length:24},(_,hour)=>({hour:hour+'시',quantity:sum(detail.filter(x=>x.hour===hour),'quantity')}));
  const dates=[...new Set(detail.map(x=>x.date))].sort().map(d=>({date:d,quantity:sum(detail.filter(x=>x.date===d),'quantity'),amount:sum(detail.filter(x=>x.date===d),'amount')}));
  return <><Header label="02 / MENU EXPLORER" title="메뉴별 판매 분석" description="전체 매출 순위에서 월별 변화, 판매 날짜와 시간까지 이어서 봅니다."/>
  <div className="toolbar"><Select label="집계 기간" value={period} onChange={setPeriod} options={[{value:'all',label:'전체 기간'},...monthOptions]}/><div className="segmented"><Button aria-pressed={metric==='amount'} className={metric==='amount'?'active':''} onClick={()=>setMetric('amount')}>매출순</Button><Button aria-pressed={metric==='quantity'} className={metric==='quantity'?'active':''} onClick={()=>setMetric('quantity')}>수량순</Button></div><CheckField className="check-label" label="아메리카노 명칭 통합" checked={group} onChange={e=>setGroup(e.target.checked)}/></div>
  <div className="ledger-workbench menu-workbench"><Section title="메뉴별 판매 내역" desc="표 머리글로 정렬하고, 메뉴명으로 검색할 수 있습니다."><Table data={rows} pageSize={7} columns={[{accessorKey:'menu',header:'메뉴',cell:i=><Button className="menu-link" aria-pressed={selected===i.getValue()} onClick={()=>setSelected(i.getValue())}>{i.getValue()}</Button>},numeric('quantity','판매 수량'),textCol('unit','단위'),numeric('amount','매출',money),numeric('average','수량당 매출',money)]} filename="메뉴별_판매내역.csv" selectedRow={r=>r.menu===selected}/></Section>  <Section eyebrow="선택 메뉴 · 월별 변화" title={selected} className="menu-detail" desc="해당 상품명에 기록된 판매량입니다. 이름·가격·구성이 바뀐 상품을 임의로 합치지 않았습니다." action={<Select label="메뉴 선택" value={selected} onChange={setSelected} options={menuNames}/>}>
  <div className="chart"><ResponsiveContainer><LineChart data={monthly} margin={{left:0,right:10,top:15}}><CartesianGrid vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis yAxisId="left" tickFormatter={v=>num(v/10000)+'만'} tickLine={false} axisLine={false}/><YAxis yAxisId="right" orientation="right" tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={(v,n)=>[n==='매출'?money(v):num(v)+(selected.includes('4구')?'팩':'개'),n]}/><Legend/><Line type="monotone" yAxisId="left" name="매출" dataKey="amount" stroke={colors[0]} strokeWidth={2.5} dot={{r:3}}/><Line type="monotone" yAxisId="right" name="판매 수량" dataKey="quantity" stroke={colors[3]} strokeWidth={2} strokeDasharray="5 4"/></LineChart></ResponsiveContainer></div>
  <Note>Payhere 월별 수량은 기존 상품 분석 화면의 건수를 원본 엑셀 수량과 대조해 일치를 확인했습니다. ‘4구’는 1팩을 1수량으로 센 값입니다. 마지막 수집일이 포함된 월은 수집 범위를 확인하세요.</Note></Section>
</div>
  <Section title="메뉴 순위 10" desc={period==='all'?'수집 전체 기간 누적':period+' 월별 실적'}><div className="chart ranking"><ResponsiveContainer><BarChart data={rows.slice(0,10)} layout="vertical" margin={{left:6,right:35}}><XAxis type="number" hide/><YAxis type="category" dataKey="menu" width={120} tickLine={false} axisLine={false} tick={{fontSize:12}}/><Tooltip contentStyle={tipStyle} formatter={v=>[metric==='amount'?money(v):num(v)+'판매단위',metric==='amount'?'매출':'판매 수량']}/><Bar dataKey={metric} radius={[0,5,5,0]} onClick={r=>setSelected(r.menu)} cursor="pointer">{rows.slice(0,10).map((r,i)=><Cell key={r.menu} fill={i===0?colors[0]:colors[1]}/>)}</Bar></BarChart></ResponsiveContainer></div><p className="footnote">막대를 누르면 선택 메뉴 상세가 바뀝니다.</p></Section>
  <div className="toolbar"><span className="subheading">토스 상세 기록</span><Select label="조회 월" value={trendMonth} onChange={setTrendMonth} options={[{value:'all',label:'토스 전체 완결일'},...D.monthly.filter(m=>m.source==='toss').map(m=>m.month)]}/></div>
  {!detail.length?<Note>이 상품명으로 연결되는 토스 시간·날짜 상세 기록이 없습니다. 아메리카노는 명칭 통합을 켜서 시간대 흐름을 확인하세요. Payhere 결제 설명만으로 메뉴 시각을 추정하지 않았습니다.</Note>:<div className="two-col"><Section title="메뉴가 팔리는 시간" desc="토스 주문 시작 시각 · 대량 주문 포함 · 부분일 제외"><div className="chart"><ResponsiveContainer><BarChart data={hours}><CartesianGrid vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="hour" interval={3} tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={v=>[num(v)+(selected.includes('4구')?'팩':'개'),'순수량']}/><Bar dataKey="quantity" fill={colors[0]} radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Section><Section title="많이 팔린 날짜" desc="날짜를 검색하거나 수량·매출순으로 정렬할 수 있습니다."><Table data={dates} pageSize={5} initialSort={[{id:'quantity',desc:true}]} columns={[textCol('date','날짜'),numeric('quantity','수량'),numeric('amount','매출',money)]} filename="선택메뉴_날짜별.csv"/></Section></div>}
  </>
}

function Prep(){
  const D=useContext(DataContext); const monthOptions=D.monthly.map(x=>x.month);
  const F=D.forecast;const [wd,setWd]=useState((new Date().getDay()+6)%7),[buffer,setBuffer]=useState(0),[lead,setLead]=useState(60),[view,setView]=useState('plan'),[manual,setManual]=useState({}),[extra,setExtra]=useState([]);
  const available=F.plans.filter(p=>p.weekday===wd).sort((a,b)=>b.expected-a.expected);
  const noSample=[...new Set(F.plans.map(p=>p.menu))].filter(m=>!available.some(p=>p.menu===m));
  const core=available.filter(p=>p.status==='준비 기준');const rare=available.filter(p=>p.status!=='준비 기준');
  const planned=[...core,...rare.filter(p=>extra.includes(p.menu))].map(p=>planRow(p,buffer,Object.hasOwn(manual,p.menu)?manual[p.menu]:null));
  const mainMetric=F.metrics.find(x=>x.menu==='전체')||{mae:null,baseline_mae:null,n:0,wape:null};
  const totals=WINDOWS.map((w,i)=>planned.reduce((s,r)=>s+r.windows[i]*(r.unit.includes('4개')?4:1),0));
  const prepExport=()=>download(`디저트_${WEEKDAYS[wd]}요일_당일준비.csv`,csv(planned.map(r=>({메뉴:r.menu,단위:r.unit,예상판매:r.expected,여유분퍼센트:buffer,당일준비:r.target,실물개수:r.physical,같은요일표본:r.same_weekday_days,...Object.fromEntries(WINDOWS.map((w,i)=>[w.label,r.windows[i]]))}))));
  const menus=[...new Set(F.plans.filter(p=>p.status==='준비 기준').map(p=>p.menu))];
  return <><Header label="03 / DESSERT PREPARATION" title="오늘 만들 디저트" description="당일 판매 원칙에 맞춘 요일별 준비 초안. 최근 토스 기록으로 계산합니다." action={<div className="head-actions"><Button className="outline" onClick={()=>window.print()}><Printer size={16}/> 인쇄</Button><Button className="primary" onClick={prepExport} disabled={!planned.length}><Download size={16}/> 준비표 저장</Button></div>}/>
  <div className="prep-summary"><div><Pill>당일 판매 · 이월 0</Pill><h2>조절 가능한 당일 준비 초안</h2><p>{F.cutoff}까지의 완결일 · 최근 {F.window_days}일 · 10만원 이상 주문 제외</p></div><div className="prep-total"><span>{WEEKDAYS[wd]}요일 당일 준비 초안</span><strong>{available.length?num(sum(planned,'physical')):'—'}<small>{available.length?'개':'표본 없음'}</small></strong><p>4구 상품은 4개로 환산 · 소량·신규 메뉴는 선택 추가</p></div></div>
  <div className="prep-controls"><div className="weekday-buttons" aria-label="준비 요일">{WEEKDAYS.map((w,i)=><Button key={w} className={i===wd?'active':''} onClick={()=>{setWd(i);setManual({})}} aria-pressed={wd===i}>{w}<small>요일</small></Button>)}</div><div className="adjust-controls"><div className="buffer-control"><div>여유분 <strong>{buffer}%</strong></div><BufferSlider value={buffer} onChange={setBuffer}/></div><div className="lead-control"><span>준비 소요 시간</span><QuantityField aria-label="준비 소요 시간 분" min={0} max={240} step={15} value={lead} onChange={v=>setLead(v)} suffix="분"/></div><Button className="text-button" onClick={()=>{setBuffer(0);setLead(60);setManual({});setExtra([])}}><RotateCcw size={15}/> 초기화</Button></div></div>
  <Note>과거 검증의 하루·메뉴 평균 오차는 {mainMetric.mae==null?"미검증":num(mainMetric.mae,2)}판매단위, 단순 최근 평균 오차는 {mainMetric.baseline_mae==null?"미검증":num(mainMetric.baseline_mae,2)}입니다. {mainMetric.mae==null?"검증할 표본이 부족합니다.":mainMetric.mae>=mainMetric.baseline_mae?"요일 모형이 단순 평균보다 정확하지 않습니다.":"검증 기간 밖의 정확도는 보장하지 않습니다."} 확정 생산량이 아닌 조절 가능한 초안입니다.</Note><div className="local-tabs"><Button aria-pressed={view==='plan'} className={view==='plan'?'active':''} onClick={()=>setView('plan')}>시간대별 준비표</Button><Button aria-pressed={view==='week'} className={view==='week'?'active':''} onClick={()=>setView('week')}>요일 비교</Button><Button aria-pressed={view==='accuracy'} className={view==='accuracy'?'active':''} onClick={()=>setView('accuracy')}>예측 검증</Button></div>
  {view==='plan'&&<>{!available.length?<Section title="이 요일은 계산할 기록이 부족합니다"><div className="empty"><CalendarDays size={32}/><p>최근 기간에 같은 요일의 매출 기록이 없습니다.<br/>예상 수량을 0으로 단정하지 않았습니다.</p></div></Section>:<>
  <Section title={`${WEEKDAYS[wd]}요일 준비표`} desc="각 시간대에 추가로 준비할 수량입니다. ‘당일 준비’를 직접 수정하면 시간대 수량도 함께 바뀝니다.">
  <p className="table-hint">좌우로 밀어 시간대별 수량을 확인하세요. 디저트 이름은 고정됩니다.</p><div className="table-scroll prep-table" tabIndex="0" role="region" aria-label="준비표 가로 스크롤"><table><thead><tr><th>디저트</th><th>예상 판매</th><th>당일 준비</th>{WINDOWS.map(w=><th key={w.label}>{w.label}<small>{w.start===0?"주문 별도 확인":deadline(w.start,lead)+" 준비 시작"}</small></th>)}<th>표본</th></tr></thead><tbody>{planned.map(r=><tr key={r.menu}><td><strong>{r.menu}</strong><small>{r.unit} {r.status==='참고용'?'· 표본 적음':''}</small></td><td>{num(r.expected,1)}</td><td><QuantityField min={0} max={999} aria-label={r.menu+' 당일 준비 수량'} value={r.target} onChange={v=>setManual({...manual,[r.menu]:v})}/></td>{r.windows.map((v,i)=><td key={i} className={v?'has-qty':''}>{v||'—'}</td>)}<td>{r.same_weekday_days}일<small>같은 요일</small></td></tr>)}</tbody><tfoot><tr><td colSpan="3">실물 개수 합계 <small>4구는 ×4</small></td>{totals.map((v,i)=><td key={i}>{v||'—'}</td>)}<td>{sum(planned,'physical')}개</td></tr></tfoot></table></div>
  {noSample.length>0&&<Note>이 요일 표본이 없어 수량을 제시하지 않은 메뉴: {noSample.join(', ')}. 최근에 등장한 메뉴는 며칠 더 기록이 쌓이면 계산할 수 있습니다.</Note>}<div className="prep-notes"><p><strong>수량 기준</strong> 평균 예상량을 반올림한 뒤 시간대 비중으로 배분했습니다. 각 시간대를 따로 올림해 당일 총량이 늘어나지 않게 했습니다.</p><p><strong>준비 시각</strong> 기본 60분은 가정입니다. 실제 제조 시간에 맞춰 조절하세요. 00–08시 칸은 밤·이른 아침 기록을 묶었으므로 주문 확인이 필요합니다.</p></div>
  {rare.length>0&&<ExtraMenus title={`신규·소량·최근 미판매 메뉴 ${rare.length}종`}><p>표본이 적거나 최근 14일간 판매가 없어 기본 준비표에서 제외했습니다. 선택하면 참고 수량을 더할 수 있습니다.</p><div className="rare-grid">{rare.map(r=><CheckField key={r.menu} checked={extra.includes(r.menu)} onChange={e=>setExtra(e.target.checked?[...extra,r.menu]:extra.filter(m=>m!==r.menu))} label={<span>{r.menu}<small>예상 {num(r.expected,1)}{r.unit} · 마지막 {r.last_observed.slice(5)}</small></span>}/>)}</div></ExtraMenus>}
  </Section><div className="two-col"><Section title="시간대별 준비 흐름" desc="4구를 낱개로 환산한 실물 기준"><div className="chart"><ResponsiveContainer><BarChart data={WINDOWS.map((w,i)=>({window:w.label,quantity:totals[i]}))}><CartesianGrid vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="window" tick={{fontSize:11}} interval={0} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tickLine={false} axisLine={false}/><Tooltip contentStyle={tipStyle} formatter={v=>[num(v)+'개','추가 준비']}/><Bar dataKey="quantity" fill={colors[0]} radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Section><Section title="판매 편차도 함께 보기" desc="최근 같은 요일의 최저–최고 순수량. 예측 구간이나 품절 확률은 아닙니다."><div className="range-list">{core.map(r=><div key={r.menu}><span>{r.menu}</span><strong>{r.history_min}–{r.history_max}<small>{r.unit}</small></strong><span className="muted">예상 {num(r.expected,1)}</span></div>)}</div></Section></div></>}
  <Note>당일 판매량은 재고 소진으로 놓친 수요를 포함하지 못합니다. 예약·단체 주문은 이 초안에 별도로 더하세요. 보관 가능 시간과 제조 배치 제약이 없어 생산 최적화까지 계산한 값은 아닙니다.</Note></>}
  {view==='week'&&<Section title="같은 메뉴, 다른 요일" desc="여유분을 적용한 당일 총 준비 수량입니다. ‘—’는 해당 요일 표본 부족입니다."><p className="table-hint">표를 좌우로 밀어 모든 요일을 확인하세요.</p><div className="table-scroll" tabIndex="0" role="region" aria-label="요일별 표 가로 스크롤"><table className="week-heatmap"><thead><tr><th>메뉴</th>{WEEKDAYS.map(w=><th key={w}>{w}요일</th>)}</tr></thead><tbody>{menus.map(m=><tr key={m}><td>{m}<small>{F.plans.find(p=>p.menu===m).unit}</small></td>{WEEKDAYS.map((w,i)=>{const p=F.plans.find(p=>p.menu===m&&p.weekday===i);const n=p?planRow(p,buffer).target:null;return <td key={w} style={{background:n?`color-mix(in srgb, var(--ss-accent) ${Math.min(90,15+n*9)}%, var(--ss-surface))`:''}}>{n??'—'}</td>})}</tr>)}</tbody></table></div><Note>최근 같은 요일 평균과 전체 평균을 섞어, 몇 번의 판매가 요일 예측을 지나치게 바꾸지 않도록 했습니다. 품목별 첫 판매 이전 날짜는 0으로 넣지 않았습니다.</Note></Section>}
  {view==='accuracy'&&<><div className="stat-grid"><Stat label="하루·메뉴 평균 오차" value={mainMetric.mae==null?'—':num(mainMetric.mae,2)} unit="판매단위" detail={`${mainMetric.n}개 메뉴·날짜 조합에서 검증`}/><Stat label="단순 최근 평균 오차" value={mainMetric.baseline_mae==null?'—':num(mainMetric.baseline_mae,2)} unit="판매단위" detail="최근 28일 기록일 평균과 비교"/><Stat label="수량 기준 오차율" value={mainMetric.wape==null?'—':num(mainMetric.wape,1)} unit="%" detail="절대 오차 합계 ÷ 실제 판매 수량"/></div><Note><strong>현재 예측은 준비 초안으로 사용하세요.</strong> {mainMetric.mae==null?"검증할 표본이 부족합니다.":mainMetric.mae>=mainMetric.baseline_mae?"최근 검증에서 요일 모형이 단순 평균보다 정확하지 않았습니다.":"표시된 과거 검증의 정확도가 향후 판매를 보장하지 않습니다."} 예상 수량을 확정 생산량으로 해석하지 않습니다.</Note><Section title="과거 날짜를 하루씩 예측한 결과" desc={`${F.holdout_start}–${F.holdout_end} · 해당 날짜 이전 자료로만 계산 · 참고용 메뉴 제외`}><Table search={false} data={F.metrics.filter(x=>x.menu!=='전체')} columns={[textCol('menu','메뉴'),numeric('n','검증일'),numeric('mae','평균 오차',v=>num(v,2)),numeric('baseline_mae','단순 평균 오차',v=>num(v,2)),{accessorKey:'wape',header:'수량 오차율',cell:i=>i.getValue()==null?'분모 0':num(i.getValue(),1)+'%'}]}/><p className="footnote">오차 단위는 메뉴 판매단위입니다. 4구 상품 1단위의 오차는 낱개 4개의 차이를 뜻합니다. 특정 메뉴의 검증일이 적으면 비교도 불안정합니다.</p></Section><Section title="계산 기준"><ol className="method-list"><li><strong>최근 56일</strong><p>완결일만 사용하고 최근 기록에 더 큰 비중을 줍니다. 21일 전 기록의 비중은 최신 기록의 절반입니다.</p></li><li><strong>비슷한 요일 + 최근 전체</strong><p>같은 요일 표본 n일의 가중치는 n / (n + 4). 나머지는 전체 요일 평균으로 보완합니다.</p></li><li><strong>일반 판매 흐름</strong><p>총액 10만원 이상 주문은 제외합니다. 해당 메뉴 판매가 없는 매출 기록일은 0으로 포함하고, 첫 판매 이전은 제외합니다.</p></li><li><strong>시간 배분</strong><p>같은 방식의 시간별 판매 비중으로 하루 수량을 나눕니다. 전체 수량은 반올림하고 잔여 수량을 소수 부분이 큰 시간대에 배분합니다.</p></li></ol><a className="source-link" href="https://otexts.com/fpp3/tscv.html" target="_blank" rel="noreferrer">검증 방법 참고: Forecasting — Time series cross-validation <ArrowUpRight size={14}/></a></Section></>}
  <div className="footnote">수정한 수량은 이 화면에서만 유지됩니다. 준비표 저장으로 현재 선택값을 보관할 수 있습니다. 전날 재고는 모든 계산에서 0입니다.</div>
  </>
}

function Changes(){
 const D=useContext(DataContext), c=D.comparison;
 const bulk=D.existing.monthly_large_order_sensitivity||[], am=D.existing.americano_before_after_28d||[];
 const change=(after,before)=>before?(after/before-1)*100:null;
 const amChange=key=>am.length===2?change(am[1][key],am[0][key]):null;
 return <><Header label="04 / CHANGE NOTES" title="매출 변화와 근거" description="관찰한 변화와 운영 원인을 구분합니다. 개인 기여 시점과 실제 운영 변경일은 아직 미확인입니다."/>
 <div className="insight-grid">{[['같은 날짜 범위 매출',c.change_pct,'부분일을 제외한 같은 월중 날짜 범위 비교입니다.'],['기록일당 매출',c.per_day_change_pct,`최근 ${c.current_days}일 / 이전 ${c.previous_days}일. 영업일 확정 값은 아닙니다.`],['개인 성과 인과관계',null,'실제 활동 날짜·사진·운영 일지 대조가 필요합니다.']].map(([title,value,desc])=><article key={title} className="insight-card"><span className="insight-date">{c.current_start}–{c.current_end}</span><h2>{title}</h2><strong>{value==null?'미확인':pct(value)}</strong><p>{desc}</p><Pill>관찰과 해석 구분</Pill></article>)}</div>
 <Section title="대량 주문을 빼면" desc="토스 기록 · 한 주문 10만원 이상을 구분합니다. 단체 고객 여부를 확정한 분류가 아닙니다."><div className="chart"><ResponsiveContainer><BarChart data={bulk}><CartesianGrid vertical={false} stroke="var(--ss-border)"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>num(v/10000)+'만'}/><Tooltip contentStyle={tipStyle} formatter={(v,n)=>[money(v),n]}/><Legend/><Bar stackId="a" name="일반 주문" dataKey="sales_without_100k_orders" fill={colors[0]}/><Bar stackId="a" name="10만원 이상 주문" dataKey="large_order_sales" fill={colors[3]}/></BarChart></ResponsiveContainer></div><Table search={false} data={bulk} columns={[textCol('month','월'),numeric('all_sales','전체',money),numeric('sales_without_100k_orders','대량 주문 제외',money),numeric('large_order_count','큰 주문 건수')]}/></Section>
 <Section title="아메리카노 포장할인 변화" desc="과거 비교 자료 · 관찰된 판매 명칭의 전환이며 실제 정책 변경일이 아닙니다.">{am.length?<><Table search={false} data={am} columns={[textCol('start','시작'),textCol('end','종료'),numeric('store_payment_days','기록일'),numeric('net_per_unit','수량당 매출',money),numeric('quantity_per_store_day','기록일당 수량',v=>num(v,1))]}/><div className="mini-metrics">{[['수량당 매출','net_per_unit'],['기록일당 수량','quantity_per_store_day'],['기록일당 매출','sales_per_store_day']].map(([label,key])=><div key={key}><span>{label}</span><strong>{amChange(key)==null?'—':pct(amChange(key))}</strong></div>)}</div></>:<Note>비교 원본이 없어 변화율을 계산하지 않았습니다.</Note>}<Note>원래 메뉴명·단가를 보존합니다. 가격 변화만으로 매출 증가나 개인의 성과를 단정하지 않습니다.</Note></Section>
 <Section title="포트폴리오 근거 체크" desc="매출 자료는 공개 포트폴리오에 자동 전달되지 않습니다."><ol className="method-list"><li><strong>활동 날짜 확인</strong><p>신메뉴·진열·홍보·단체 주문 제안의 실제 실행 날짜와 본인의 역할을 확인합니다.</p></li><li><strong>같은 조건으로 비교</strong><p>기록일 수·메뉴 구성·대량 주문·POS 전환을 함께 확인합니다.</p></li><li><strong>근거를 대조</strong><p>사진·게시물·운영 일지와 매출 변화 시점을 대조합니다.</p></li><li><strong>공개할 문장 별도 검토</strong><p>검증된 사실만 골라 외부 공개 여부를 결정합니다.</p></li></ol><a className="outline" href="/sungso/sohee/portfolio/">포트폴리오 구성 예시 보기 <ArrowUpRight size={16}/></a></Section>
 </>
}
function DataPage(){
 const D=useContext(DataContext);
 return <><Header label="05 / DATA LIBRARY" title="수집 범위와 데이터 관리" description="앞으로는 토스 원본만 갱신합니다. 과거 페이히어 자료는 보존합니다."/>
 <UpdatePanel/>
 <div className="source-cards"><Section title="토스 · 앞으로의 기록" desc={`상세 원본 마지막 날짜 ${D.end}`}><Pill>완결일 {D.complete_through}까지</Pill><ul className="plain-list"><li>메뉴별 날짜·주문 시간·수량·금액</li><li>중복되는 날짜 범위만 교체·누적</li><li>부분일: {D.partial_dates.join(', ')||'없음'}</li></ul><Note>앱 화면에서 확인한 합계는 상세 거래를 대체하지 않습니다. 새 토스 원본을 받아 검증하기 전에는 매출을 보충하지 않습니다.</Note></Section><Section title="페이히어 · 과거 기록" desc="보관된 원본과 월별 화면을 대조한 자료"><ul className="plain-list"><li>과거 일별·월별 매출과 월별 메뉴 수량</li><li>메뉴별 거래 시각은 제공되지 않음</li><li>메뉴 시간대·준비 예측은 토스만 사용</li></ul><Note>4구 상품은 1팩이 1판매단위입니다. 준비표에서만 실물 4개로 구분합니다.</Note></Section></div>
 <Section title="갱신·수집 범위"><Table search={false} data={D.monthly} columns={[textCol('month','기간'),textCol('source','출처'),numeric('record_days','기록일'),{accessorKey:'partial',header:'수집 상태',cell:i=>i.getValue()?'부분월':'수집 완료'}]}/><p className="footnote">분석 생성일 {D.generated_at} · 분석 생성일과 원본 수집일은 다를 수 있습니다.</p></Section>
 <Section title="원본 대조 기록"><div className="validation-grid">{D.files.map(f=><div key={f.file}><Check size={20}/><div><strong>{f.file}</strong><p>{f.start}–{f.end}</p><small>SHA-256 {f.sha256.slice(0,16)}…</small></div></div>)}</div><div className="download-row"><Button className="outline" onClick={()=>download('통합_일별매출.csv',csv(D.daily))}><Download size={16}/> 일별 매출 CSV</Button><Button className="outline" onClick={()=>download('통합_메뉴월별.csv',csv(D.menu_monthly))}>메뉴 월별 CSV</Button><Button className="outline" onClick={()=>download('예측검증.csv',csv(D.forecast.metrics))}>예측 검증 CSV</Button></div><Note>다운로드 파일에는 비공개 매출이 포함됩니다. 파일의 공유 범위를 직접 확인하세요.</Note></Section>
 <Section title="해석의 한계"><ul className="plain-list"><li>기록 없는 날은 휴무로 단정하지 않습니다.</li><li>원가·폐기·품절 기록이 없어 이익이나 놓친 수요를 계산하지 않습니다.</li><li>기여 시점·운영 변경일은 미확인입니다.</li><li>예측 오차와 표본 부족을 준비 화면에서 함께 표시합니다.</li></ul></Section></>
}
const pages=[{id:'overview',label:'전체 매출',en:'Overview',icon:LayoutDashboard,component:Overview},{id:'menus',label:'메뉴 분석',en:'Menu explorer',icon:Coffee,component:Menus},{id:'prep',label:'디저트 준비',en:'Daily preparation',icon:Croissant,component:Prep},{id:'changes',label:'변화와 성과',en:'Change notes',icon:ChartNoAxesCombined,component:Changes},{id:'data',label:'데이터 관리',en:'Data library',icon:Database,component:DataPage}];
export function SalesApp({data,route='overview',status='Firebase 회원 전용'}){
 const [navOpen,setNavOpen]=useState(false);
 const selected=pages.find(p=>p.id===route); const Page=selected?.component;
 useEffect(()=>{document.title=`${selected?.label||'페이지 없음'} · 양정커피`;},[route]);
 return <DataContext.Provider value={data}><div className={'app page-'+route}>
  <a href="#main" className="skip-link">본문으로 이동</a>
  <header className="app-header"><div className="app-identity"><a href={BASE} className="brand"><span className="brand-mark"><Coffee size={24}/></span><strong>양정커피</strong></a><a className="workspace-link" href="/sungso/sohee/workspace/">소희 작업실</a></div><span className="connection-status">{status}</span></header>
  <div className="navigation-shell"><Button className="mobile-menu" aria-label="페이지 메뉴" aria-expanded={navOpen} aria-controls="sales-navigation" onClick={()=>setNavOpen(!navOpen)}><span>{selected?.label||'매출 분석'}</span><MenuIcon size={20}/></Button><nav id="sales-navigation" aria-label="매출 분석" className={'primary-nav '+(navOpen?'open':'')}>{pages.map(p=><a href={BASE+p.id+'/'} key={p.id} className={route===p.id?'active':''} aria-current={route===p.id?'page':undefined} onClick={()=>setNavOpen(false)}>{p.label}</a>)}</nav></div>
  <main id="main" tabIndex="-1"><div className="page-content">{!Page?<Section title="페이지를 찾을 수 없어요"><a href={BASE}>전체 매출로</a></Section>:!data?<><Header title="아직 저장된 매출이 없습니다" description="회원 전용 Firebase 저장소를 확인했습니다. 검증된 분석본을 이전하거나 새 원본을 가져오면 표시됩니다."/><UpdatePanel/></>:<Page/>}</div><footer>양정커피 <span>매출을 읽고, 오늘의 준비를 결정합니다.</span><a href={BASE+'data/'}>자료 기준 <ArrowUpRight size={13}/></a></footer></main>
 </div></DataContext.Provider>
}
export class ErrorBoundary extends React.Component{constructor(p){super(p);this.state={error:false}}static getDerivedStateFromError(){return {error:true}}render(){return this.state.error?<div className="empty"><h1>화면을 불러오지 못했습니다.</h1><p>저장된 자료의 형식을 확인해주세요.</p><Button onClick={()=>location.reload()}>새로고침</Button></div>:this.props.children}}
