import React, { useId, useState, useRef } from 'react';
import { MantineProvider, createTheme, Button as MantineButton, Select as MantineSelect, Checkbox, Slider, NumberInput, TextInput, PasswordInput, FileInput, Accordion, ActionIcon } from '@mantine/core';
import { Calendar, DatesProvider, DateTimePicker } from '@mantine/dates';
import { CalendarDays, ChevronDown, Search, Upload, Check, Minus, Plus } from 'lucide-react';
import 'dayjs/locale/ko';
import { toLocalMinute } from './ui-datetime.mjs';

const theme=createTheme({fontFamily:'var(--ss-font-sans)',fontFamilyMonospace:'var(--ss-font-mono)',primaryColor:'blue',defaultRadius:'md',focusRing:'auto',headings:{fontFamily:'var(--ss-font-sans)'},components:{Select:{defaultProps:{comboboxProps:{withinPortal:false},allowDeselect:false,checkIconPosition:'right'}},Popover:{defaultProps:{withinPortal:false}},Tooltip:{defaultProps:{withinPortal:false}},Button:{defaultProps:{size:'sm',radius:'md'}},Input:{defaultProps:{size:'sm',radius:'md'}}}});
const tokens=()=>({variables:{'--mantine-font-family':'var(--ss-font-sans)'},light:{
  '--mantine-color-body':'var(--ss-bg)','--mantine-color-text':'var(--ss-text)','--mantine-color-dimmed':'var(--ss-muted)',
  '--mantine-color-default':'var(--ss-surface)','--mantine-color-default-color':'var(--ss-text)','--mantine-color-default-border':'var(--ss-border-strong)','--mantine-color-default-hover':'var(--ss-soft)',
  '--mantine-color-placeholder':'var(--ss-muted)','--mantine-color-anchor':'var(--ss-link)',
  '--mantine-color-blue-0':'var(--ss-soft)','--mantine-color-blue-1':'var(--ss-soft)','--mantine-color-blue-2':'var(--ss-accent)','--mantine-color-blue-3':'var(--ss-accent)','--mantine-color-blue-4':'var(--ss-border-strong)','--mantine-color-blue-5':'var(--ss-link)','--mantine-color-blue-6':'var(--ss-link)','--mantine-color-blue-7':'var(--ss-link)','--mantine-color-blue-8':'var(--ss-on-accent)','--mantine-color-blue-9':'var(--ss-text)',
  '--mantine-color-blue-filled':'var(--ss-link)','--mantine-color-blue-filled-hover':'var(--ss-on-accent)','--mantine-color-blue-light':'var(--ss-soft)','--mantine-color-blue-light-hover':'var(--ss-hover)','--mantine-color-blue-light-color':'var(--ss-link)',
  '--mantine-primary-color-filled':'var(--ss-link)','--mantine-primary-color-light':'var(--ss-soft)','--mantine-primary-color-light-color':'var(--ss-link)',
  '--mantine-color-disabled':'var(--ss-soft)','--mantine-color-disabled-color':'var(--ss-muted)','--mantine-color-disabled-border':'var(--ss-border)',
},dark:{}});
export function SalesUI({children,env}){return <MantineProvider env={env} theme={theme} forceColorScheme="light" cssVariablesResolver={tokens}><DatesProvider settings={{locale:'ko',firstDayOfWeek:1,weekendDays:[0,6]}}>{children}</DatesProvider></MantineProvider>}
export function Button({className='',children,...props}){return <MantineButton variant={className.includes('primary')?'filled':'default'} className={'sales-button '+className} {...props}>{children}</MantineButton>}
export function Select({label,value,onChange,options,disabled}){const id=useId();return <div className="select-label"><span id={id}>{label}</span><MantineSelect disabled={disabled} aria-labelledby={id} aria-label={label} value={value} onChange={v=>v!==null&&onChange(v)} data={options.map(o=>typeof o==='string'?o:o)} rightSection={<ChevronDown size={15}/>} className="sales-select" searchable={options.length>12} nothingFoundMessage="일치하는 항목이 없습니다"/></div>}
export function SearchField({value,onChange,placeholder}){return <TextInput className="search-field" aria-label="표 검색" placeholder={placeholder} value={value} onChange={onChange} leftSection={<Search size={16}/>} />}
export function CheckField({label,...props}){return <Checkbox label={label} radius="sm" size="sm" {...props}/>}
export function QuantityField({onChange,...props}){const handlers=useRef(null);const label=props['aria-label']||'수량';return <div className="quantity-field"><ActionIcon className="quantity-step" variant="default" aria-label={label+' 줄이기'} disabled={props.disabled||Number(props.value)<=Number(props.min??0)} onClick={()=>handlers.current?.decrement()}><Minus size={14}/></ActionIcon><NumberInput handlersRef={handlers} hideControls allowNegative={false} allowDecimal={false} allowLeadingZeros={false} clampBehavior="strict" onChange={v=>onChange(Number(v)||0)} {...props}/><ActionIcon className="quantity-step" variant="default" aria-label={label+' 늘리기'} disabled={props.disabled||Number(props.value)>=Number(props.max??Infinity)} onClick={()=>handlers.current?.increment()}><Plus size={14}/></ActionIcon></div>}
export function BufferSlider({value,onChange}){return <Slider className="buffer-slider" thumbLabel="준비 여유분" min={0} max={30} step={5} value={value} onChange={onChange} label={v=>`${v}%`} marks={[{value:0,label:'0%'},{value:15,label:'15%'},{value:30,label:'30%'}]} thumbSize={19} />}
export function ExtraMenus({title,children}){return <Accordion className="rare-menus" variant="separated" chevron={<ChevronDown size={17}/>}><Accordion.Item value="extra"><Accordion.Control>{title}</Accordion.Control><Accordion.Panel>{children}</Accordion.Panel></Accordion.Item></Accordion>}
export function SourceFile({value,onChange,disabled}){return <FileInput label="이 컴퓨터에서 받은 토스 ZIP" placeholder="토스 ZIP 파일 선택" accept=".zip,application/zip" value={value} onChange={onChange} clearable clearButtonProps={{'aria-label':'선택한 ZIP 지우기'}} leftSection={<Upload size={17}/>} required disabled={disabled}/>}
export function SourcePassword({value,onChange,disabled}){return <PasswordInput label="ZIP 암호" autoComplete="off" value={value} onChange={onChange} disabled={disabled} visibilityToggleButtonProps={{'aria-label':'ZIP 암호 표시 전환'}}/>}
export function SourceDateTime({value,onChange,disabled}){return <DateTimePicker label="원본 추출 시각 (한국 시간)" placeholder="날짜와 시간을 선택하세요" value={value?value.replace('T',' ')+':00':null} onChange={v=>onChange(toLocalMinute(v))} valueFormat="YYYY.MM.DD HH:mm" leftSection={<CalendarDays size={17}/>} clearable clearButtonProps={{'aria-label':'추출 시각 지우기'}} required disabled={disabled} popoverProps={{withinPortal:false,position:'bottom-start',width:312}} monthLabelFormat="YYYY년 M월" yearLabelFormat="YYYY년" nextLabel="다음 달" previousLabel="이전 달" submitButtonProps={{'aria-label':'추출 시각 선택 완료',children:<Check size={16}/>}} timePickerProps={{withDropdown:true,withSeconds:false,popoverProps:{withinPortal:false},hoursInputLabel:'시',minutesInputLabel:'분'}}/>}

export function SalesCalendar({month,onMonthChange,months,daily,start,end,selectedDates,onSelectDate,dayStatus}){
  const [selected,setSelected]=useState(null);
  const records=new Map(daily.map(row=>[row.date,row]));const max=Math.max(1,...daily.map(row=>row.amount));
  const record=selected?.startsWith(month)?records.get(selected):null;
  const label=date=>{const row=records.get(date);return `${date} · ${row?`${Number(row.amount).toLocaleString('ko-KR')}원${row.partial_day?' · 부분일':''}`:'선택 범위 밖 또는 수집 기록 없음'}`};
  return <div className="sales-calendar"><Calendar date={month+'-01'} onDateChange={v=>{const next=v.slice(0,7);const target=next>month?months.find(m=>m>=next):[...months].reverse().find(m=>m<=next);if(target)onMonthChange(target);setSelected(null)}} minDate={start} maxDate={end} maxLevel="month" hideOutsideDates highlightToday={false} monthLabelFormat="YYYY년 M월" nextLabel="다음 매출 월" previousLabel="이전 매출 월" getDayProps={date=>({disabled:!records.has(date),selected:selectedDates?selectedDates.includes(date):selected===date,onClick:()=>{setSelected(date);onSelectDate?.(date)},'aria-label':label(date),'aria-description':records.has(date)&&dayStatus?dayStatus(records.get(date)).hint:undefined,title:label(date)+(records.has(date)&&dayStatus?' · '+dayStatus(records.get(date)).hint:''),'data-partial':records.get(date)?.partial_day||undefined,style:records.has(date)&&records.get(date).amount>0?{background:`color-mix(in srgb,var(--ss-accent) ${15+65*records.get(date).amount/max}%,var(--ss-surface))`}:undefined})} renderDay={date=>{const row=records.get(date);return <span className="sales-day">{row&&dayStatus&&<i aria-hidden="true" className={'calendar-detail-dot '+dayStatus(row).kind}/>}<span>{Number(date.slice(8))}</span><strong>{row?row.amount?(row.amount/10000).toLocaleString('ko-KR',{maximumFractionDigits:1,minimumFractionDigits:1}):'—':''}</strong>{row?.partial_day&&<small>부분</small>}</span>}}/>
  <div className="calendar-reading" aria-live="polite"><CalendarDays size={17}/>{record?<span><strong>{record.date} · {Number(record.amount).toLocaleString('ko-KR')}원</strong><small>{record.partial_day?'부분일 · 아직 하루가 끝나지 않은 기록입니다.':'완결일 기록 · 원가는 포함하지 않습니다.'}</small></span>:<span>날짜를 누르면 정확한 금액을 확인할 수 있습니다.<small>단위 만원 · —는 매출 0 또는 결제 기록 없음</small></span>}</div></div>
}
